// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(PsychiatricHospitalContext))]
    [Migration("20221216124220_InitMigartion")]
    partial class InitMigartion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstMeeting")
                        .HasColumnType("datetime2");

                    b.Property<int>("FrequencyTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PsycotherapistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PsycotherapistId");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nulla sed neque malesuada, faucibus est non, luctus elit. Sed ultrices sem justo, convallis convallis ex sagittis sit amet. Cras at mauris in lectus semper placerat sit amet nec metus.",
                            FirstMeeting = new DateTime(2022, 12, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FrequencyTime = 0,
                            Name = "Ronald E. Tinsley depression",
                            PsycotherapistId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mauris ac odio dui. ",
                            FirstMeeting = new DateTime(2022, 12, 13, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            FrequencyTime = 0,
                            Name = "Edward J. Reynolds post-traumatic syndrome",
                            PsycotherapistId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Duis non tellus sed velit imperdiet lacinia. ",
                            FirstMeeting = new DateTime(2022, 12, 15, 13, 20, 0, 0, DateTimeKind.Unspecified),
                            FrequencyTime = 0,
                            Name = "Lloyd D. Smith amnesia",
                            PsycotherapistId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cras varius tortor a diam pulvinar tempor. Aliquam vel bibendum turpis. ",
                            FirstMeeting = new DateTime(2022, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FrequencyTime = 0,
                            Name = "Corine W. Daniels paranoia",
                            PsycotherapistId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Quisque nunc quam, lacinia ut efficitur et, dictum eu dui. Aliquam dapibus sem eget nisi pellentesque, non eleifend ipsum bibendum.",
                            FirstMeeting = new DateTime(2022, 12, 16, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            FrequencyTime = 0,
                            Name = "Christine R. Carlson addiction",
                            PsycotherapistId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Nulla ut finibus tellus. Donec ultrices sem eros, tincidunt ultrices leo malesuada ut. Vivamus ultricies eros eget enim lobortis eleifend. Mauris consectetur, ipsum at condimentum semper, elit elit egestas nibh, id suscipit sem diam sed neque. ",
                            FirstMeeting = new DateTime(2022, 12, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FrequencyTime = 0,
                            Name = "Tricia C. Kirkpatrick depression",
                            PsycotherapistId = 1
                        });
                });

            modelBuilder.Entity("Model.Psycotherapist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Psycotherapists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Herentalsebaan 335, 2100 Antwerpen",
                            Name = "Zach Curtis",
                            Password = "1ps"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Eyendijkstraat 22, 2100 Antwerpen",
                            Name = "Max Thomson",
                            Password = "2ps"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Apollostraat 31, 2140 Antwerpen",
                            Name = "Eva Reyes",
                            Password = "3ps"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Lange Beeldekensstraat 267, 2060 Antwerpen",
                            Name = "Farhan Greene",
                            Password = "4ps"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Arenaplein 62 A, 2100 Antwerpen",
                            Name = "Lorna Carpenter",
                            Password = "5ps"
                        });
                });

            modelBuilder.Entity("Model.Meeting", b =>
                {
                    b.HasOne("Model.Psycotherapist", "Psycotherapist")
                        .WithMany("Calendar")
                        .HasForeignKey("PsycotherapistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psycotherapist");
                });

            modelBuilder.Entity("Model.Psycotherapist", b =>
                {
                    b.Navigation("Calendar");
                });
#pragma warning restore 612, 618
        }
    }
}
